version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: product_services_db
    restart: always
    environment:
       POSTGRES_DB: product_services_db
       POSTGRES_USER: product_services_user
       POSTGRES_PASSWORD: product_services_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_ready -U product_services_user -d product_services_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    container_name: product_services_app
    command: >
       sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 
              0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=product_services_db
      - DB_USER=product_services_user
      - DB_PASSWORD=product_services_pass
      - DB_HOST=db
      - DB_PORT=5432
volumes:
  postgres_data:

    
